name: bonch-click
services:
  click:
    build:
      context: . 
      dockerfile: src/click-app/Dockerfile 

    depends_on:
      - db

    networks:
      - main-net

  api:
    build:
      context: . 
      dockerfile: src/api/Dockerfile 
    ports:
      - "8000:8000"

    depends_on:
      - db

    networks:
      - main-net

    develop:
      watch:
        - action: sync+restart
          path: ./src/api
          target: /app/src/api
        - action: rebuild
          path: pyproject.toml 

  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - main-net

  migrator:
    build:
      context: .
      dockerfile: migrator/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["alembic", "upgrade", "head"]  # можно менять при вызове

    networks:
      - main-net

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

networks:
  main-net:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data:

