"""remove primary autoinc id, now email is primary key

Revision ID: 5ba535d5cc6b
Revises: f5de643accda
Create Date: 2025-04-28 22:46:52.096709

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ba535d5cc6b"
down_revision: str | None = "f5de643accda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
